version: '3.3'
services:
  nextjs:
    build:
      context: .
      args:
        - NEXT_PUBLIC_BASE_API_URL=https://tracking.hxrsmurf.info
        - NODE_ENV=production
    ports:
      - 3001:3000
