version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "personal-tracker-nextjs1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-148nh4a4hjibx"
s3_prefix = "personal-tracker-nextjs1"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []