# CFT Name: personal-tracker-nextjs
Description: Personal Tracking - NextJS
Resources:
  Table:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: user
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE

  User:
    Type: 'AWS::IAM::User'
    Properties:
      Policies:
        - PolicyName: DynamoDB
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'dynamodb:*'
                Resource: !GetAtt Table.Arn